apiVersion: v1
kind: Service
metadata:
  name: hello-chronosphere
  labels:
    app: hello-chronosphere
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: hello-chronosphere
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 31081

